language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
os:
  - linux
before_install:
  - sudo apt-get update
  - sudo apt-get install -q libatlas3gf-base libatlas-dev liblapack-dev gfortran
  - sudo apt-get install libeigen3-dev
  - gcc --version
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test [ENTER]
  - sudo apt-get update
  - sudo apt-get install gcc-4.9 g++-4.9
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-4.9
  - gcc --version
  - sudo apt-get install -qq python-numpy python-scipy
install:
  - pip install --upgrade pip
  - pip install cython
  - travis_wait pip install -r requirements.txt
  - python setup.py install
  - pip install coveralls
script: coverage run --source=robo -m unittest discover robo/test -v
after_success: coveralls
